### ISSUE TITLE
pypi package is missing VERSION

### ISSUE THREAD

**Issue by codl** [jonbeebe/frontmatter#1]
when trying to install frontmatter from pypi i get this error:

```
Collecting frontmatter
  Using cached frontmatter-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ydhxyl_1/frontmatter/setup.py", line 13, in <module>
        with open(path.join(here, 'VERSION'), encoding='utf-8') as f:
      File "/usr/lib/python3.6/codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-ydhxyl_1/frontmatter/VERSION'
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ydhxyl_1/frontmatter/
```

it seems that `VERSION` was not included in the package. It should be added to `MANIFEST.in`

**Comment by jonbeebe** [comment]
Thanks for reporting this issue! VERSION was added on March 20: https://github.com/jonbeebe/frontmatter/commit/c0abf5d4af611ae2382dc6712f063b7876727801
